version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: mk/nodejs-mysql
    depends_on:
      - mysql
    environment: 
      - HOST="mk-mysql-app"
      - USER="mk"
      - PASSWORD="mk"
      - DB="mk"
      - PORT=4040
    ports: 
      - 4041:4040
    container_name: nodejs-mysql-app
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mk
      - MYSQL_PASSWORD=mk
      - MYSQL_DATABASE=mk
    container_name: mk-mysql-app
  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 4042:8080
  
    


